### ISSUE TITLE
Add provided text files

### ISSUE THREAD

**Issue by mikewideman** [rigatoni/linguine#23]

**Comment by mikewideman** [comment]
Choose based on:

-well-known in canon
-represent distinct varieties and intersts
-shakespeare, whitman, douglass, sci-fi, jonathan swift
-provide genre labels

**Comment by mikewideman** [comment]
- Macbeth
- The Merchant of Venice
- Leaves of Grass
- My Bondage and My Freedom
- The Crystal Crypt
- Gulliver's Travels
- The Canterbury Tales

**Comment by danrlavoie** [comment]
http://www.gutenberg.org/ebooks/41445 Frankenstein
http://www.gutenberg.org/ebooks/76 Adventures of Huckleberry Finn
http://www.gutenberg.org/ebooks/74 Tom Sawyer
http://www.gutenberg.org/ebooks/120 Treasure Island
http://www.gutenberg.org/ebooks/42 Dr. Jekyll and Mr. Hide
